@baseUrl = http://localhost:3000
###authLogin
# @name authLogin
POST {{@baseUrl}}/auth/login

{
  "email": "user@email.com",
  "password": "123456"
}

### Read one user
# @name readOneUser
GET {{{{baseUrl}}}}/user/123
Content-Type: application/json